fix: testing

diff --git a/.actor/Dockerfile b/.actor/Dockerfile
--- a/.actor/Dockerfile
+++ b/.actor/Dockerfile
@@ -1,9 +1,105 @@
-# Specify the base Docker image. You can read more about
-# the available images at https://crawlee.dev/docs/guides/docker-images
-# You can also use any other image from Docker Hub.
-FROM apify/actor-node-puppeteer-chrome:18 AS builder
 
-RUN apt-get install -y ffmpeg
+ARG NODE_VERSION=18
+# Use bullseye to be consistent across node versions.
+FROM node:${NODE_VERSION}-bullseye-slim AS builder
+
+LABEL maintainer="support@apify.com" Description="Base image for Apify actors using headless Chrome"
+ENV DEBIAN_FRONTEND=noninteractive
+
+# This image was inspired by https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker
+
+# Install latest Chrome dev packages and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
+# Note: this also installs the necessary libs to make the bundled version of Chromium that Puppeteer installs work.
+RUN apt-get update \
+    && apt-get install -y wget gnupg unzip ca-certificates --no-install-recommends \
+    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
+    && sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
+    && sh -c 'echo "deb http://ftp.us.debian.org/debian bullseye main non-free" >> /etc/apt/sources.list.d/fonts.list' \
+    && apt-get update \
+    && apt-get purge --auto-remove -y unzip \
+    && apt-get install -y \
+    fonts-freefont-ttf \
+    ffmpeg \
+    fonts-ipafont-gothic \
+    fonts-kacst \
+    fonts-liberation \
+    fonts-thai-tlwg \
+    fonts-wqy-zenhei \
+    git \
+    libxss1 \
+    lsb-release \
+    procps \
+    xdg-utils \
+    xvfb \
+    --no-install-recommends \
+    # Disable chrome auto updates, based on https://support.google.com/chrome/a/answer/9052345
+    && mkdir -p /etc/default && echo 'repo_add_once=false' > /etc/default/google-chrome \
+    \
+    # Install chrome
+    && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -nv \
+    && apt install --fix-missing -yq ./google-chrome-stable_current_amd64.deb && rm ./google-chrome-stable_current_amd64.deb \
+    \
+    # Add user so we don't need --no-sandbox.
+    && groupadd -r myuser && useradd -r -g myuser -G audio,video myuser \
+    && mkdir -p /home/myuser/Downloads \
+    && chown -R myuser:myuser /home/myuser \
+    \
+    && mkdir -p /etc/opt/chrome/policies/managed \
+    && echo '{ "CommandLineFlagSecurityWarningsEnabled": false }' > /etc/opt/chrome/policies/managed/managed_policies.json \
+    && echo '{ "ComponentUpdatesEnabled": false }' > /etc/opt/chrome/policies/managed/component_update.json \
+    \
+    # Globally disable the update-notifier.
+    && npm config --global set update-notifier false \
+    # Cleanup
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -rf /src/*.deb \
+    && apt-get clean -y && apt-get autoremove -y \
+    && rm -rf /root/.npm \
+    # This is needed to remove an annoying error message when running headful.
+    && mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix
+
+# Run everything after as non-privileged user.
+USER myuser
+WORKDIR /home/myuser
+
+# Copy source code and xvfb script
+COPY --chown=myuser:myuser package.json main.js puppeteer_*.js start_xvfb_and_run_cmd.sh /home/myuser/
+
+# Uncomment to skip the chromium download when installing puppeteer. If you do,
+# you'll need to launch puppeteer with:
+#     browser.launch({executablePath: 'google-chrome'})
+# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
+
+# Sets path to Chrome executable, this is used by Apify.launchPuppeteer()
+ENV APIFY_CHROME_EXECUTABLE_PATH=/usr/bin/google-chrome
+
+# Tell the crawlee cli that we already have browers installed, so it skips installing them
+ENV CRAWLEE_SKIP_BROWSER_INSTALL=1
+
+# Tell Node.js this is a production environemnt
+ENV NODE_ENV=production
+
+# Enable Node.js process to use a lot of memory (actor has limit of 32GB)
+# Increases default size of headers. The original limit was 80kb, but from node 10+ they decided to lower it to 8kb.
+# However they did not think about all the sites there with large headers,
+# so we put back the old limit of 80kb, which seems to work just fine.
+ENV NODE_OPTIONS="--max_old_space_size=30000 --max-http-header-size=80000"
+
+# Install default dependencies, print versions of everything
+RUN npm --quiet set progress=false \
+    && npm install --only=prod --no-optional --no-package-lock --prefer-online \
+    && echo "Installed NPM packages:" \
+    && (npm list --only=prod --no-optional || true) \
+    && echo "Node.js version:" \
+    && node --version \
+    && echo "NPM version:" \
+    && npm --version \
+    && echo "Google Chrome version:" \
+    && bash -c "$APIFY_CHROME_EXECUTABLE_PATH --version"
+
+# Set up xvfb
+ENV DISPLAY=:99
+ENV XVFB_WHD=1920x1080x24+32
 
 # Copy just package.json and package-lock.json
 # to speed up the build using Docker layer cache.
@@ -19,9 +115,6 @@ COPY --chown=myuser . ./
 # Install all dependencies and build the project.
 # Don't audit to speed up the installation.
 RUN npm run build
-
-# Create final image
-FROM apify/actor-node-puppeteer-chrome:18
 
 # Copy just package.json and package-lock.json
 # to speed up the build using Docker layer cache.
@@ -41,7 +134,7 @@ RUN npm --quiet set progress=false \
     && rm -r ~/.npm
 
 # Copy built JS files from builder image
-COPY --from=builder --chown=myuser /home/myuser/dist ./dist
+COPY --chown=myuser /home/myuser/dist ./dist
 
 # Next, copy the remaining files and directories with the source code.
 # Since we do this after NPM install, quick build will be really fast
